export const FETCH_RECIPES = "FETCH_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const ADD_RECIPE_TO_LIST = "ADD_RECIPE_TO_LIST";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const DELETE_RECIPE_FROM_LIST = "DELETE_RECIPE_FROM_LIST";
export const UPDATE_RECIPE_FROM_LIST = "UPDATE_RECIPE_FROM_LIST";